### PR TITLE
Prepare release 0.3.2

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by guewen** [comment]
@sylvain-garancher 
Sorry if I was too bold to merge this one.
I think that since April, a release is well deserved as we are blocked by #4 on several projects.

Could you push the release on Pypi? Since we have no answer here https://github.com/OCA/odoo-sphinx-autodoc/pull/4#issuecomment-212835680, I'm not sure who have the rights to push packages apart you.

**Comment by Garamotte** [comment]
@guewen : I just pushed a new release on Pypi.

For the record, I just had to execute :

```
git pull
python setup.py sdist upload
```

I think at least @gurneyalex has the rights to push new releases.

**Comment by guewen** [comment]
Thanks a lot!

**Comment by yvaucher** [comment]
@sylvain-garancher Thanks, that's good to know

**Pull request merged**
