### PR TITLE
Don't fail if a module in addons path is not a python module

### LINKED ISSUE #3: Fails if non module directories are present in ODOO_ADDONS_PATH directory (exemple with setup folder)
https://travis-ci.org/OCA/geospatial/jobs/124475258

For exemple with the `setup` folder introduced in repositories for packaging:

```
Exception occurred:
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/sphinxodoo/ext/autodoc.py", line 27, in load_odoo_modules
    module_name, openerp.tools.config['addons_path'].split(','))
ImportError: No module named setup
```

### PR DESCRIPTION
**Pull request by yvaucher**
simply ignore it

This fix travis failure whon `setup` directory is present

Fixes #3

### CODE REVIEW

**Comment by yvaucher** [comment]
ping @sbidoul @guewen

**Comment by sbidoul** [comment]
LGTM. Another way to do it is look for `__openerp__.py` and check the installable flag at the same time, to ignore unported modules. Not sure if installableness is important here.

:+1:

**Comment by guewen** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by guewen** [comment]
@sylvain-garancher could you publish a new release on pypi?

**Comment by Garamotte** [comment]
I have the rights on Pypi, but OCA is also owner.

Publishing a new version needs updating setup.py and CHANGES.txt files.
I think it's simpler if an OCA admin can do this.

**Comment by yvaucher** [comment]
I guess the boad have access to this pypi account?
@sbidoul @gurneyalex @elicoidal @max3903 

I prepared the release here https://github.com/OCA/odoo-sphinx-autodoc/pull/5
@sylvain-garancher is there anything needed ?

**Pull request merged**
